# generated by datamodel-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-03-23T11:54:47+00:00

from __future__ import annotations

from datetime import date, datetime, time
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, RootModel, confloat, conint, constr


class Name(BaseModel):
    first_name: Optional[str] = None
    last_name: Optional[str] = None


class Address(BaseModel):
    address1: Optional[str] = None
    address2: Optional[str] = None
    city: Optional[str] = None
    country: Optional[str] = None
    province: Optional[str] = None
    zip: Optional[str] = None


class Source(Enum):
    """
    Payment method source type.
    """

    credit_card = 'credit_card'
    paypal = 'paypal'
    bank_transfer = 'bank_transfer'


class PaymentMethods(BaseModel):
    source: Source
    """
    Payment method source type.
    """
    brand: str
    """
    Brand of the payment method (e.g., Visa, MasterCard, etc.).
    """
    last_four: constr(pattern=r'^[0-9]{4}$')
    """
    Last four digits of the payment method.
    """
    id: str
    """
    Unique identifier for the payment method.
    """


class Membership(Enum):
    regular = 'regular'
    silver = 'silver'
    gold = 'gold'


class Payment(BaseModel):
    payment_id: str
    """
    The payment id stored in user profile, such as 'credit_card_7815826', 'gift_card_7815826', 'certificate_7815826'.
    """
    amount: float
    """
    The amount to be paid.
    """


class Passenger(BaseModel):
    first_name: str
    """
    The first name of the passenger, such as 'Noah'.
    """
    last_name: str
    """
    The last name of the passenger, such as 'Brown'.
    """
    dob: str
    """
    The date of birth of the passenger in the format 'YYYY-MM-DD', such as '1990-01-01'.
    """


class ScheduledFlight(BaseModel):
    flight_number: str
    """
    ScheduledFlight number, such as 'HAT001'.
    """
    origin: str
    """
    The IATA code for the origin city, such as 'SFO'.
    """
    destination: str
    """
    The IATA code for the destination city, such as 'JFK'.
    """
    scheduled_departure_time_est: time
    """
    Estimated scheduled detaprture time in HH:MM:SS format (24-hour clock).
    """
    scheduled_arrival_time_est: time
    """
    Estimated scheduled arrival time in HH:MM:SS format (24-hour clock).
    """


class FlightPrices(BaseModel):
    """
    Price per seat in different classes.
    """

    basic_economy: Optional[confloat(ge=0.0)] = None
    economy: Optional[confloat(ge=0.0)] = None
    business: Optional[confloat(ge=0.0)] = None


class FlightSeats(BaseModel):
    """
    Number of available seats per class.
    """

    basic_economy: Optional[conint(ge=0)] = None
    economy: Optional[conint(ge=0)] = None
    business: Optional[conint(ge=0)] = None


class FlightStatus(Enum):
    landed = 'landed'
    available = 'available'
    cancelled = 'cancelled'
    flying = 'flying'


class FlightInstanceId(BaseModel):
    flight_number: str
    """
    Flight number, such as 'HAT001'.
    """
    date: str
    """
    The date for the flight in the format 'YYYY-MM-DD', such as '2024-05-01'.
    """


class FlightInstance(FlightInstanceId):
    status: FlightStatus
    actual_departure_time_est: Optional[datetime] = None
    """
    Estimated actual departure time in ISO 8601 format (YYYY-MM-DDTHH:MM:SS).
    """
    estimated_arrival_time_est: Optional[datetime] = None
    """
    Estimated arrival time in ISO 8601 format (YYYY-MM-DDTHH:MM:SS).
    """
    available_seats: Optional[FlightSeats] = None
    prices: Optional[FlightPrices] = None


class FoundFlight(ScheduledFlight):
    available_seats: FlightSeats
    prices: FlightPrices


class ReservationFlight(FlightInstanceId):
    origin: Optional[str] = None
    """
    The IATA code for the origin city, such as 'SFO'.
    """
    destination: Optional[str] = None
    """
    The IATA code for the destination city, such as 'JFK'.
    """
    price: Optional[float] = None
    """
    The flight leg
    """


class FlightType(Enum):
    one_way = 'one_way'
    round_trip = 'round_trip'


class Insurance(Enum):
    True_ = True
    False_ = False


class ResevationStatus(Enum):
    cancelled = 'cancelled'


class Cabin(Enum):
    """
    A cabin
    """

    basic_economy = 'basic_economy'
    economy = 'economy'
    business = 'business'


class CalculateParametersQuery(BaseModel):
    expression: str


class UpdateReservationBaggagesRequest(BaseModel):
    total_baggages: int
    """
    The total number of baggage items included in the reservation.
    """
    nonfree_baggages: int
    """
    The number of non-free baggage items included in the reservation.
    """
    payment_id: str
    """
    The payment id stored in user profile, such as 'credit_card_7815826', 'gift_card_7815826', 'certificate_7815826'.
    """


class UpdateReservationFlightsRequest(BaseModel):
    cabin: Cabin
    flights: List[FlightInstanceId]
    """
    An array of objects containing details about each piece of flight in the ENTIRE new reservation. Even if the a flight segment is not changed, it should still be included in the array.
    """
    payment_id: str
    """
    The payment id stored in user profile, such as 'credit_card_7815826', 'gift_card_7815826', 'certificate_7815826'.
    """


class UpdateReservationPassengersRequest(BaseModel):
    passengers: List[Passenger]
    """
    An array of objects containing details about each piece of flight in the ENTIRE new reservation. Even if the a flight segment is not changed, it should still be included in the array.
    """


class SearchDirectFlightParametersQuery(BaseModel):
    origin: Optional[str] = None
    destination: Optional[str] = None
    date: Optional[date] = None


class SearchDirectFlightResponse(RootModel[List[FoundFlight]]):
    root: List[FoundFlight]


class SearchOnestopFlightParametersQuery(SearchDirectFlightParametersQuery):
    pass


class SearchOnestopFlightResponse(RootModel[List[List[FoundFlight]]]):
    root: List[List[FoundFlight]]


class ListAirportsResponse(RootModel[List[Dict[str, Any]]]):
    root: List[Dict[str, Any]]


class SendCertificateParametersQuery(BaseModel):
    amount: float


class ThinkRequest(BaseModel):
    thought: str
    """
    A thought to think about.
    """


class TransferToHumanAgentsRequest(BaseModel):
    summary: str
    """
    A summary of the user's issue.
    """


class User(BaseModel):
    name: Name
    address: Optional[Address] = None
    email: str
    dob: Optional[date] = None
    """
    Date of birth
    """
    payment_methods: Optional[Dict[str, PaymentMethods]] = None
    """
    A collection of payment methods, keyed by unique identifiers.
    """
    saved_passengers: Optional[List[Passenger]] = None
    membership: Membership
    reservations: Optional[List[str]] = None
    """
    List of associated reservation ids
    """


class ReservationBase(BaseModel):
    user_id: str
    """
    The ID of the user to book the reservation, such as 'sara_doe_496'.
    """
    origin: str
    """
    The IATA code for the origin city, such as 'SFO'.
    """
    destination: str
    """
    The IATA code for the destination city, such as 'JFK'.
    """
    flight_type: FlightType
    cabin: Cabin
    passengers: List[Passenger]
    """
    An array of objects containing details about each passenger.
    """
    total_baggages: int
    """
    The total number of baggage items included in the reservation.
    """
    nonfree_baggages: int
    """
    The number of non-free baggage items included in the reservation.
    """
    insurance: Insurance


class CreateReservation(ReservationBase):
    flights: List[FlightInstanceId]
    """
    An array of objects containing details about each piece of flight.
    """
    payment_methods: List[Payment]
    """
    An array of objects containing details about each payment method.
    """


class Reservation(ReservationBase):
    flights: List[ReservationFlight]
    """
    An array of objects containing details about each piece of flight.
    """
    payment_history: List[Payment]
    """
    An array of objects containing details about each piece of flight.
    """
    created_at: datetime
    """
    Timestamp indicating when the entity was created, in ISO 8601 format.
    """
    status: Optional[ResevationStatus] = None

# Tool interfaces
from typing import Any, Dict, List, Protocol


class TaubenchAirline(Protocol):

    def calculate(self, query: CalculateParametersQuery) ->str:
        """Calculate the result of a mathematical expression."""
        pass

    def book_reservation(self, request: CreateReservation) ->Reservation:
        """Creates a reservation"""
        pass

    def get_reservation_details(self, reservation_id: str) ->Reservation:
        """Get the reservation."""
        pass

    def cancel_reservation(self, reservation_id: str) ->Reservation:
        """Cancel the whole reservation."""
        pass

    def update_reservation_baggages(self, reservation_id: str, request:
        UpdateReservationBaggagesRequest) ->Reservation:
        """Update the baggage information of a reservation."""
        pass

    def update_reservation_flights(self, reservation_id: str, request:
        UpdateReservationFlightsRequest) ->Reservation:
        """Update the flight information of a reservation."""
        pass

    def update_reservation_passengers(self, reservation_id: str, request:
        UpdateReservationPassengersRequest) ->Reservation:
        """Update the passenger information of a reservation."""
        pass

    def get_scheduled_flight(self, flight_id: str) ->ScheduledFlight:
        """Get the details of a scheduled flight. For example, returns the flight origin, destination, scheduled detaprture and arrival times."""
        pass

    def search_direct_flight(self, query: SearchDirectFlightParametersQuery
        ) ->List[FoundFlight]:
        """Search direct flights between two cities on a specific date."""
        pass

    def search_onestop_flight(self, query: SearchOnestopFlightParametersQuery
        ) ->List[List[FoundFlight]]:
        """Search one-stop flights between two cities on a specific date."""
        pass

    def get_flight_instance(self, flight_id: str, date: datetime.date
        ) ->FlightInstance:
        """Get the details of a flight instance in a specific date. For example, returns the flight status, available seats and prices."""
        pass

    def list_airports(self) ->List[Any]:
        """List all airports available in the system"""
        pass

    def get_user_details(self, user_id: str) ->User:
        """Get the details of an user."""
        pass

    def send_certificate(self, user_id: str, query:
        SendCertificateParametersQuery) ->str:
        """Send a certificate to a user. Be careful!"""
        pass

    def think(self, request: ThinkRequest) ->str:
        """Use the tool to think about something. It will not obtain new information or change the database, but just append the thought to the log. Use it when complex reasoning is needed."""
        pass

    def transfer_to_human_agents(self, request: TransferToHumanAgentsRequest
        ) ->str:
        """Transfer the user to a human agent, with a summary of the user's issue. Only transfer if the user explicitly asks for a human agent, or if the user's issue cannot be resolved by the agent with the available tools."""
        pass

